name: Test
on:
  push

env:
  my_name: "Debjit Chakra"

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing my workflow variable ${my_name}"
  test_job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing a new workflow job2"
