name: Test
on:
  push

env:
  my_name: "Debjit Chakra"

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing my workflow variable ${{env.my_name}}"
  test_job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls -l /home/hackerguru/.kube
          kubectl --kubeconfig=/home/hackerguru/.kube/config get pods
